server {
    listen 80;
    root /app;
    index code.php;

    location ~ \.php$ {
        fastcgi_pass serveur:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /app$fastcgi_script_name;
    }
}

